language: node_js
dist: trusty
node_js:
  - '10'

python:
  - '3.7'
before_install:
  - pip install pandas dfply

addons:

branches:
  only:
    - master

# build the webapp into ./dist
script:
  - scripts/build-travis.sh

# the script statement for each deploy refer to the deploy.sh script because the script tag in the deploy section
# only supports one command...
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $TRAVIS_TOKEN
  target-branch: gh-pages
  on:
    branch: master
