language: node_js
dist: trusty
node_js:
  - '10'

python:
  - '3.7'
before_install:
  - sudo apt-get -y install pyenv
  - pyenv 3.7
  - pip install dfply

  #  - sudo apt-get -y install python3 python3-pip python3-pandas python3-numpy wget

addons:

branches:
  only:
    - master

# build the webapp into ./dist
script:
  - bash scripts/build-travis.sh

# the script statement for each deploy refer to the deploy.sh script because the script tag in the deploy section
# only supports one command...
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $TRAVIS_TOKEN
  target-branch: gh-pages
  on:
    branch: master
